---
title: "Demonstration"
output: html_document
date: "2023-08-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 

Beantwoord de volgende vraag in niet meer dan 300 woorden:

Hoe zouden we het schrijfproces kunnen diagnosticeren?

Je hebt 45 minuten om de opdracht te voltooien. Je kunt elke online bron of website gebruiken die je wilt, maar geen ChatGPT (of vergelijkbaar) en geen Google Translate (of vergelijkbaar).

## Schrijfproduct

Het beoordelen van schrijfvaardigheden gaat vaak over het schrijfproduct, de tekst die de student schrijft. De tekst wordt geëvalueerd met behulp van een rubriek die verschillende kenmerken van een tekst toelicht op een bepaalde aantal scores en criteria. Feedback aan de schrijver gaat dus over wat goed en slecht is in de tekst zelf. Dit is belangrijk informatie, maar soms is het niet direct bruikbaar en praktische.

Informatie over wat kan tijdens het schrijfproces anders worden doen, zou echter nuttig zijn om een beter product te schrijven. Een manier waarop wij kunnen dit doen is door gebruik van 'revisietests', waarbij de kennis en vaardigheden die gebruikt worden in het herzien van een tekst wordt beoordeeld door indirecte meerkeuze-vragen. Bijvoorbeeld een vraag waarbij een student een zin moet lezen en dan moet beslissen in welk gedeelte zit een fout.

Toch gaat revisietests slechts over één van de processen die plaatsvinden terwijl wij schrijven. Zulke tests zeggen bijvoorbeeld niets van de planning van een tekst. Maar nieuwe technologieën zoals keystroke analyse en computerschermopname programma's maken het veel makkelijker om het schrijfproces te verkennen, in onderzoek en toch ook in assessment. 

Een paar recente onderzoeksartikelen over collaboratieve schrijven (twee schrijvers samen schrijven) hebben gebruikt gemaakt van een rubriek waarin zoals het schrijfproduct als het collaboratieve gedragen (het proces) is beoordeeld. Hoewel dit voor gebruik in het klaslokaal bedoeld is, in de toekomst kunnen wij zo'n rubriek gebruik maken in combinatie met screen-capture opnames of keystrokelogging technologie om het schrijfproces beter te diagnosticeren. 

297 words
